version: "3"

services:
    #抢票服务
    ticket:
        image: train_ticket:1.0
        environment:
            - PYTHONUNBUFFERED=1
            - CAPTCHALOCAL=1
            - TICKET_TYPE=1
            - STATION_DATES=2023-01-20
            - STATION_TRAINS=
            - FROM_STATION=
            - TO_STATION=
            - SET_TYPE=
            - TICKET_PEOPLES=
            - USERNAME=
            - PASSWORD=
            - REQ_HOST=captcha:80
            - CORP_ID=
            - CORP_SECRET=
            - AGENT_ID=
        container_name: ticket
        depends_on:
            - captcha
        networks:
            - 12306network
        restart: on-failure
    #打码服务器
    captcha:
        image: 1995chen/train_code_server:stable #请根据需要修改image
        environment:
            - WORKERS=1 #gunicorn works 默认为1可以根据服务器配置自行调整
            - PYTHONUNBUFFERED=1
        container_name: captcha
        networks:
            - 12306network
        restart: unless-stopped
networks:
    12306network:
        driver: bridge

